hangman_animation = [
    [
        '            ',
        '            ',
        '            ',
        '            ',
        '            ',
        '            ',
        '            ',
    ],
    [
        '            ',
        '            ',
        '            ',
        '            ',
        '            ',
        '            ',
        'XXXXXXXXXXXX',
    ],
    [
        '  X         ',
        '  X         ',
        '  X         ',
        '  X         ',
        '  X         ',
        '  X         ',
        'XXXXXXXXXXXX',
    ],
    [
        '  XXXXXX    ',
        '  X         ',
        '  X         ',
        '  X         ',
        '  X         ',
        '  X         ',
        'XXXXXXXXXXXX',
    ],
    [
        '  XXXXXX    ',
        '  X    X    ',
        '  X         ',
        '  X         ',
        '  X         ',
        '  X         ',
        'XXXXXXXXXXXX',
    ],
    [
        '  XXXXXX    ',
        '  X    X    ',
        '  X    O    ',
        '  X         ',
        '  X         ',
        '  X         ',
        'XXXXXXXXXXXX',
    ],
    [
        '  XXXXXX    ',
        '  X    X    ',
        '  X    O    ',
        '  X    |    ',
        '  X         ',
        '  X         ',
        'XXXXXXXXXXXX',
    ],
    [
        '  XXXXXX    ',
        '  X    X    ',
        '  X    O    ',
        '  X   -|    ',
        '  X         ',
        '  X         ',
        'XXXXXXXXXXXX',
    ],
    [
        '  XXXXXX    ',
        '  X    X    ',
        '  X    O    ',
        '  X   -|-   ',
        '  X         ',
        '  X         ',
        'XXXXXXXXXXXX',
    ],
    [
        '  XXXXXX    ',
        '  X    X    ',
        '  X    O    ',
        '  X   -|-   ',
        '  X   (     ',
        '  X         ',
        'XXXXXXXXXXXX',
    ],
    [
        '  XXXXXX    ',
        '  X    X    ',
        '  X    O    ',
        '  X   -|-   ',
        '  X   ( )   ',
        '  X         ',
        'XXXXXXXXXXXX',
    ],
]
